name: Convert raw files to CSV

on:
  workflow_dispatch:
  workflow_call:

jobs:
  convert-to-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "latest"

      - name: Processing files to csv
        run: |
          mkdir -p data/csv
          uv run python main.py -a

      - name: Commit and push changes
        if: github.ref == 'refs/heads/main'
        run: |
          ./scripts/commit-and-push.sh \
            "Converting files to CSV format - $(date +'%Y-%m-%d')" \
            data/csv

  call-update-technology:
    needs: convert-to-csv
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/update_technology.yml
    permissions:
      contents: write
